spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melihhtasci/microservice-architecture/tree/main/local-properties
          default-label: main
server:
  port: 8888

