spring:
  application:
    name: currency-exchange
  cloud:
    config:
      import-check:
        enabled: false
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8100
